#
# MM25 Configuration
#
out_dir: '/data/nih/mm25'
version: '1.0'

fassoc_dir: '/data/nih/fassoc'

# If true, each dataset will contribute the same amount to the final combined
# p-values / scores. In cases where multiple covariates are assessed for a dataset,
# the "best" value (e.g. minimum p-value) will be used for each gene.
normalize_dataset_contributions: false
