#
# MM25 Configuration
#
out_dir: '/data/proj/mm25'
version: '3.2'

fassoc_dir: '/data/fassoc/mm25/3.2'

# location of processed gene expression data; used to construct a combined expr
# data matrix for convenience
expr_data:
  geo: "/data/clean/geo/3.1/*/*_gene_expr_nr.feather"
  mmrf: "/data/clean/mmrf/IA15/rnaseq/MMRF_CoMMpass_IA15a_E74GTF_HtSeq_Gene_Counts_1_BM_symbols_nr_CPM.feather"

# If true, each dataset will contribute the same amount to the final combined
# p-values / scores. In cases where multiple covariates are assessed for a dataset,
# the "best" value (e.g. minimum p-value) will be used for each gene.
normalize_dataset_contributions: true

# gene set settings;
# the specified input gmt files should be the same used in the original MM25 generation
# for each size, N, a gmt file will be constructed containing
# only the top N MM25-ranked gene sets;
gene_sets:
  gmts: '/data/clean/msigdb/v7.0/*.gmt'
  sizes: [50, 100, 150, 200, 250, 500, 750, 1000]

#
# clustering settings
#

# maximum number of missing values allowed for a gene to be used in clustering
# covariates
clustering:
  method: 'gaussian_mixture'
  num_clusters: 2
  max_missing: 5

