#
# MM25 Configuration
#
out_dir: '/data/nih/mm25'
version: '2.4'

fassoc_dir: '/data/nih/fassoc/mm25/2.0'

# If true, each dataset will contribute the same amount to the final combined
# p-values / scores. In cases where multiple covariates are assessed for a dataset,
# the "best" value (e.g. minimum p-value) will be used for each gene.
normalize_dataset_contributions: true

# gene set settings;
# the specified input gmt files should be the same used in the original MM25 generation
# for each size, N, a gmt file will be constructed containing
# only the top N MM25-ranked gene sets;
gene_sets:
  gmts: '/data/gmt/custom/msigdb/v7.0/*.gmt'
  sizes: [50, 100, 150, 200, 250, 500, 750, 1000]

#
# clustering settings
#

# maximum number of missing values allowed for a gene to be used in clustering
# covariates
clustering:
  method: 'kmeans'
  num_clusters: 2
  max_missing: 5

